version: '3.8'

services:
    air-mongo:
        image: mongo
        command: mongod --config /etc/mongo/mongod.conf #ggf. //etc !!!
        restart: always
        ports:
            - "8888:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongoadmin
            MONGO_INITDB_ROOT_PASSWORD: secret
        networks:
            air-net:
                aliases:
                    - air-mongo
                    - db
        volumes:
            - "${AIR_LOG_PATH}:/var/log/mongodb"
            - "${AIR_CONF_PATH}://etc/mongo"
            - "air-volume://data/db"

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
            ME_CONFIG_MONGODB_ADMINPASSWORD: secret
            ME_CONFIG_MONGODB_SERVER: air-mongo
        networks:
            air-net:
                aliases:
                    - mongo-express
                    - db-admin


networks:
    air-net:
        driver: bridge
        labels:
            com.some-test.description: "The air-google mongo network"
        #name: air-net-tigkeiten


volumes:
    air-volume:

